import { NSQFCourse } from './types';

export const NSQF_COURSES_DATASET: NSQFCourse[] = [
  // APPAREL & GARMENTS
  {
    id: 'nsqf-app-01',
    title: 'Self-Employed Tailor',
    qpCode: 'AMH/Q1947',
    nsqfLevel: 4,
    sector: 'Apparel & Garmenting',
    durationHours: 300,
    durationText: '3 Months (300 hrs)',
    eligibility: '8th Pass with basic stitching orientation',
    minEducation: '8th Pass',
    skillsTaught: ['Pattern Making', 'Garment Construction', 'Costing & Pricing', 'Machine Maintenance', 'Customer Relations'],
    careerRoles: ['Boutique Owner', 'Independent Tailor', 'Custom Garment Maker'],
    description: 'Specialized course for individuals aiming to set up an independent tailoring enterprise or boutique, covering measurement taking, fabric cutting, stitching, and business management.',
    certifyingBody: 'Apparel Made-Ups & Home Furnishing Sector Skill Council (AMHSSC)',
    officialCourseUrl: 'https://nqr.gov.in/qualification-packs/self-employed-tailor-1',
    source: 'National Qualifications Register (NQR) / AMHSSC',
    verificationStatus: 'VERIFIED_OFFICIAL',
    isVerifiedGovernmentData: true
  },
  {
    id: 'nsqf-app-02',
    title: 'Sewing Machine Operator',
    qpCode: 'AMH/Q0301',
    nsqfLevel: 3,
    sector: 'Apparel & Garmenting',
    durationHours: 240,
    durationText: '2.5 Months (240 hrs)',
    eligibility: '5th Pass / Basic Literacy',
    minEducation: 'Below 8th',
    skillsTaught: ['Single/Double Needle Machine Operation', 'Stitching Techniques', 'Quality Check', 'Safety Standards'],
    careerRoles: ['Garment Factory Sewing Operator', 'Assembly Line Worker'],
    description: 'Hands-on training for operating single and double needle lockstitch sewing machines in garment export houses and factories.',
    certifyingBody: 'AMHSSC / National Skill Development Corporation (NSDC)',
    officialCourseUrl: 'https://nqr.gov.in/qualification-packs/sewing-machine-operator-0',
    source: 'NQR / NSDC Official Registry',
    verificationStatus: 'VERIFIED_OFFICIAL',
    isVerifiedGovernmentData: true
  },

  // NIELIT DIGITAL & IT COURSES
  {
    id: 'nsqf-nielit-01',
    title: 'NIELIT Certificate Course in Computer Concepts (CCC)',
    qpCode: 'NIELIT/CCC/L3',
    nsqfLevel: 3,
    sector: 'IT-ITeS & Digital',
    durationHours: 80,
    durationText: '1 Month (80 hrs)',
    eligibility: 'No Minimum Education / Basic Literacy',
    minEducation: 'Below 8th',
    skillsTaught: ['Computer Basics', 'MS Office & Word', 'Spreadsheets & Excel', 'Internet & E-Governance', 'Digital Financial Services'],
    careerRoles: ['Office Assistant', 'Digital Helper', 'CSC Operator'],
    description: 'Official NIELIT NSQF Level 3 certified course designed to impart basic digital literacy and enable rural SC beneficiaries to utilize e-governance and online portals.',
    certifyingBody: 'National Institute of Electronics & Information Technology (NIELIT)',
    officialCourseUrl: 'https://www.nielit.in/content/nsqf',
    source: 'NIELIT Official NSQF Framework Portal',
    verificationStatus: 'VERIFIED_OFFICIAL',
    isVerifiedGovernmentData: true
  },
  {
    id: 'nsqf-nielit-02',
    title: 'NIELIT O Level (IT) / Junior Software Developer',
    qpCode: 'NIELIT/O-LEVEL/L4',
    nsqfLevel: 4,
    sector: 'IT-ITeS & Digital',
    durationHours: 520,
    durationText: '1 Year / 6 Months intensive (520 hrs)',
    eligibility: '12th Pass or ITI Certificate',
    minEducation: '12th Pass',
    skillsTaught: ['Python Programming', 'Web Design (HTML/CSS/JS)', 'IoT & Embedded Systems', 'Database Management'],
    careerRoles: ['Junior Programmer', 'Web Designer', 'IT Support Technician'],
    description: 'Government recognised NIELIT O Level qualification equivalent to Foundation Level course in Computer Applications.',
    certifyingBody: 'NIELIT / Ministry of Electronics & IT (MeitY)',
    officialCourseUrl: 'https://www.nielit.in/content/nsqf',
    source: 'NIELIT / MeitY Official Site',
    verificationStatus: 'VERIFIED_OFFICIAL',
    isVerifiedGovernmentData: true
  },

  // ELECTRONICS & RENEWABLE ENERGY
  {
    id: 'nsqf-elec-01',
    title: 'Solar Panel Installation Technician (Suryamitra)',
    qpCode: 'ELE/Q5901',
    nsqfLevel: 4,
    sector: 'Renewable Energy & Electronics',
    durationHours: 300,
    durationText: '3 Months (300 hrs)',
    eligibility: '10th Pass or ITI in Electrical/Wireman',
    minEducation: '10th Pass',
    skillsTaught: ['PV Panel Mounting', 'Inverter Wiring', 'Rooftop Structural Rigging', 'System Testing & Maintenance', 'Electrical Safety'],
    careerRoles: ['Solar Installer', 'Rooftop Solar Technician', 'Clean Energy Micro-Entrepreneur'],
    description: 'Government aligned Suryamitra training for rooftop and agricultural solar panel deployment and maintenance under PM-Surya Ghar.',
    certifyingBody: 'Skill Council for Green Jobs (SCGJ)',
    officialCourseUrl: 'https://nqr.gov.in/qualification-packs/solar-pv-installer-suryamitra',
    source: 'NQR Green Jobs Portal',
    verificationStatus: 'VERIFIED_OFFICIAL',
    isVerifiedGovernmentData: true
  },
  {
    id: 'nsqf-elec-03',
    title: 'Mobile Phone Hardware Repair Technician',
    qpCode: 'ELE/Q8104',
    nsqfLevel: 4,
    sector: 'Electronics',
    durationHours: 300,
    durationText: '3 Months (300 hrs)',
    eligibility: '10th Pass',
    minEducation: '10th Pass',
    skillsTaught: ['SMD Soldering', 'PCB Circuit Diagnostics', 'Display & Battery Replacement', 'Software Flashing', 'Shop Management'],
    careerRoles: ['Mobile Repair Specialist', 'Mobile Repair Shop Proprietor'],
    description: 'Comprehensive hardware and software repair training for mobile devices, enabling self-employment.',
    certifyingBody: 'Electronics Sector Skills Council of India (ESSCI)',
    officialCourseUrl: 'https://nqr.gov.in/qualification-packs/mobile-phone-hardware-repair-technician',
    source: 'ESSCI / NQR Registry',
    verificationStatus: 'VERIFIED_OFFICIAL',
    isVerifiedGovernmentData: true
  },

  // IT & DIGITAL SKILLS
  {
    id: 'nsqf-it-01',
    title: 'Domestic Data Entry Operator',
    qpCode: 'SSC/Q2212',
    nsqfLevel: 4,
    sector: 'IT-ITeS & Digital',
    durationHours: 400,
    durationText: '4 Months (400 hrs)',
    eligibility: '10th Pass with basic English typing',
    minEducation: '10th Pass',
    skillsTaught: ['Alphanumeric Data Typing (35+ wpm)', 'MS Office & Google Workspace', 'Data Verification', 'Cyber Hygiene', 'Office Communication'],
    careerRoles: ['Data Entry Operator', 'Office Assistant', 'Common Service Centre (CSC) Operator'],
    description: 'Prepares beneficiaries for administrative desk roles in government departments, banks, and private firms.',
    certifyingBody: 'IT-ITeS Sector Skills Council NASSCOM',
    officialCourseUrl: 'https://nqr.gov.in/qualification-packs/domestic-data-entry-operator-1',
    source: 'NASSCOM / NQR Official Portal',
    verificationStatus: 'VERIFIED_OFFICIAL',
    isVerifiedGovernmentData: true
  },

  // AGRICULTURE & ALLIED
  {
    id: 'nsqf-agro-01',
    title: 'Organic Grower',
    qpCode: 'AGR/Q0801',
    nsqfLevel: 4,
    sector: 'Agriculture & Allied',
    durationHours: 200,
    durationText: '2 Months (200 hrs)',
    eligibility: '5th Pass / Farmer background preferred',
    minEducation: 'Below 8th',
    skillsTaught: ['Vermi-composting', 'Organic Bio-Pesticides (Jeevamrut)', 'Crop Rotation', 'Organic Certification Process', 'Direct Market Linkage'],
    careerRoles: ['Organic Farmer', 'Bio-Input Producer', 'FPO Lead Farmer'],
    description: 'Teaches low-cost sustainable organic farming techniques to maximize agricultural yields and market value.',
    certifyingBody: 'Agriculture Skill Council of India (ASCI)',
    officialCourseUrl: 'https://nqr.gov.in/qualification-packs/organic-grower-0',
    source: 'ASCI / NQR Official Registry',
    verificationStatus: 'VERIFIED_OFFICIAL',
    isVerifiedGovernmentData: true
  },

  // BEAUTY & WELLNESS
  {
    id: 'nsqf-bw-02',
    title: 'Beauty Therapist & Salon Manager',
    qpCode: 'BWC/Q0202',
    nsqfLevel: 4,
    sector: 'Beauty & Wellness',
    durationHours: 350,
    durationText: '3.5 Months (350 hrs)',
    eligibility: '10th Pass',
    minEducation: '10th Pass',
    skillsTaught: ['Advanced Facial Treatments', 'Bridal Makeup', 'Hair Styling', 'Salon Setup & Financial Management'],
    careerRoles: ['Senior Beauty Therapist', 'Home Parlour Owner', 'Salon Franchise Operator'],
    description: 'Advanced entrepreneurial course enabling setup of home-based or commercial beauty parlours with PM-AJAY GIA toolkit support.',
    certifyingBody: 'Beauty & Wellness Sector Skill Council (B&WSSC)',
    officialCourseUrl: 'https://nqr.gov.in/qualification-packs/beauty-therapist-0',
    source: 'B&WSSC / NQR Registry',
    verificationStatus: 'VERIFIED_OFFICIAL',
    isVerifiedGovernmentData: true
  },

  // HEALTHCARE & ALLIED
  {
    id: 'nsqf-health-01',
    title: 'General Duty Assistant (GDA)',
    qpCode: 'HSS/Q5101',
    nsqfLevel: 4,
    sector: 'Healthcare & Nursing Support',
    durationHours: 400,
    durationText: '4 Months (400 hrs)',
    eligibility: '10th Pass',
    minEducation: '10th Pass',
    skillsTaught: ['Patient Care & Hygiene', 'Vital Signs Monitoring', 'Infection Control', 'Basic First Aid', 'Hospital Ward Protocol'],
    careerRoles: ['Hospital Attendant', 'Nursing Home Assistant', 'Home Healthcare Attendant'],
    description: 'High-demand healthcare support course placing workers in private hospitals, clinics, and eldercare facilities.',
    certifyingBody: 'Healthcare Sector Skill Council (HSSC)',
    officialCourseUrl: 'https://nqr.gov.in/qualification-packs/general-duty-assistant-0',
    source: 'HSSC / NQR Official Portal',
    verificationStatus: 'VERIFIED_OFFICIAL',
    isVerifiedGovernmentData: true
  }
];
