import { Opportunity } from './types';

export const DEMO_DATA_DISCLAIMER = "Demo Data — Replace with verified government/API data before deployment.";
export const PM_AJAY_PATHWAY_NOTE = "This opportunity may be relevant to a PM-AJAY/GIA livelihood-support pathway, subject to applicable eligibility and approval.";

export interface DistrictCentroid {
  district: string;
  state: string;
  latitude: number;
  longitude: number;
}

export const DISTRICT_CENTROIDS: Record<string, DistrictCentroid> = {
  // Tamil Nadu
  'Theni': { district: 'Theni', state: 'Tamil Nadu', latitude: 10.0104, longitude: 77.4768 },
  'Madurai': { district: 'Madurai', state: 'Tamil Nadu', latitude: 9.9252, longitude: 78.1198 },
  'Dindigul': { district: 'Dindigul', state: 'Tamil Nadu', latitude: 10.3673, longitude: 77.9803 },
  'Coimbatore': { district: 'Coimbatore', state: 'Tamil Nadu', latitude: 11.0168, longitude: 76.9558 },
  'Tiruppur': { district: 'Tiruppur', state: 'Tamil Nadu', latitude: 11.1085, longitude: 77.3411 },
  'Chennai': { district: 'Chennai', state: 'Tamil Nadu', latitude: 13.0827, longitude: 80.2707 },
  'Salem': { district: 'Salem', state: 'Tamil Nadu', latitude: 11.6643, longitude: 78.1460 },
  'Erode': { district: 'Erode', state: 'Tamil Nadu', latitude: 11.3410, longitude: 77.7172 },

  // Andhra Pradesh
  'Vizianagaram': { district: 'Vizianagaram', state: 'Andhra Pradesh', latitude: 18.1067, longitude: 83.3956 },
  'Vijayawada': { district: 'Vijayawada', state: 'Andhra Pradesh', latitude: 16.5062, longitude: 80.6480 },
  'Guntur': { district: 'Guntur', state: 'Andhra Pradesh', latitude: 16.3067, longitude: 80.4365 },
  'Tirupati': { district: 'Tirupati', state: 'Andhra Pradesh', latitude: 13.6288, longitude: 79.4192 },

  // Karnataka
  'Bengaluru': { district: 'Bengaluru', state: 'Karnataka', latitude: 12.9716, longitude: 77.5946 },
  'Mysuru': { district: 'Mysuru', state: 'Karnataka', latitude: 12.2958, longitude: 76.6394 },

  // Kerala
  'Kochi': { district: 'Kochi', state: 'Kerala', latitude: 9.9312, longitude: 76.2673 },
  'Thiruvananthapuram': { district: 'Thiruvananthapuram', state: 'Kerala', latitude: 8.5241, longitude: 76.9366 },

  // Other Existing Project Districts
  'Sitapur': { district: 'Sitapur', state: 'Uttar Pradesh', latitude: 27.5684, longitude: 80.6829 },
  'Gaya': { district: 'Gaya', state: 'Bihar', latitude: 24.7914, longitude: 85.0002 },
  'Solapur': { district: 'Solapur', state: 'Maharashtra', latitude: 17.6599, longitude: 75.9064 }
};

export const OPPORTUNITIES_DATASET: Opportunity[] = [
  // ==========================================
  // TAMIL NADU - THENI (Focus Demo District)
  // ==========================================
  {
    id: 'opp-tn-theni-01',
    name: 'Theni Apparel & Tailoring Training Center',
    type: 'training',
    state: 'Tamil Nadu',
    district: 'Theni',
    city: 'Theni Allinagaram',
    latitude: 10.0250,
    longitude: 77.4850, // ~4.8 km from 10.0104, 77.4768
    skills: ['Tailoring', 'Sewing', 'Hand Stitching', 'Garment Finishing', 'Pattern Cutting'],
    educationRequired: '8th Pass',
    nsqfLevel: 4,
    courseName: 'Sewing Machine Operator (AMH/Q0301)',
    provider: 'District Skill Development Office & Govt ITI Theni',
    careerGoal: 'self-employment',
    estimatedMonthlyIncome: 14000,
    eligibility: ['Age 18-35', 'Basic literacy', 'SC community preference under PM-AJAY GIA'],
    description: 'Certified NSQF Level 4 apparel tailoring training with motorized single needle lockstitch machine operation and PM-AJAY toolkit grant eligibility.',
    contactPhone: '+91 4546 252 011',
    contactEmail: 'iti-theni.tn@gov.in',
    address: 'Collectorate Complex Road, Allinagaram, Theni 625531',
    isVerified: true
  },
  {
    id: 'opp-tn-theni-02',
    name: 'Theni PM-AJAY Tailoring & Boutique Enterprise Pathway',
    type: 'livelihood',
    state: 'Tamil Nadu',
    district: 'Theni',
    city: 'Periyakulam',
    latitude: 10.0380,
    longitude: 77.5120, // ~7.2 km from center
    skills: ['Tailoring', 'Garment Design', 'Boutique Setup', 'Uniform Stitching', 'Fabric Sourcing'],
    educationRequired: '8th Pass',
    nsqfLevel: 4,
    courseName: 'Self Employed Tailor (AMH/Q1947)',
    provider: 'Tamil Nadu Urban & Rural Livelihood Mission (TNSRLM)',
    careerGoal: 'self-employment',
    estimatedMonthlyIncome: 18000,
    eligibility: ['Prior stitching experience', 'SC household member', 'PM-AJAY GIA toolkit applicant'],
    description: 'Self-employment incubation unit providing sewing machinery equipment subsidy, working capital credit linkage, and local uniform procurement orders.',
    contactPhone: '+91 4546 231 404',
    contactEmail: 'tnsrlm.theni@tn.gov.in',
    address: 'Near Old Bus Stand, Periyakulam Road, Theni District 625601',
    isVerified: true
  },
  {
    id: 'opp-tn-theni-03',
    name: 'Theni Garment Production Assistant & Machinist',
    type: 'job',
    state: 'Tamil Nadu',
    district: 'Theni',
    city: 'Bodinayakanur',
    latitude: 10.0650,
    longitude: 77.5450, // ~11.5 km from center
    skills: ['Tailoring', 'Industrial Sewing', 'Overlock Machine', 'Quality Inspection'],
    educationRequired: '10th Pass',
    nsqfLevel: 3,
    courseName: 'Apparel Quality Checker & Machine Operator',
    provider: 'Cardamom City Garments & Export Unit (MSME Partner)',
    careerGoal: 'job',
    estimatedMonthlyIncome: 13500,
    eligibility: ['10th pass preferred', 'Minimum 6 months stitching experience', 'Day shift availability'],
    description: 'Full-time wage employment on automated garment assembly lines. Includes EPF, ESI health cover, and performance production incentives.',
    contactPhone: '+91 4546 280 912',
    contactEmail: 'careers@cardamomgarments.com',
    address: 'Industrial Estate, Subburaj Nagar, Bodinayakanur, Theni 625513',
    isVerified: true
  },
  {
    id: 'opp-tn-theni-04',
    name: 'Theni Rural Agro & Food Processing Collective',
    type: 'livelihood',
    state: 'Tamil Nadu',
    district: 'Theni',
    city: 'Chinnamanur',
    latitude: 9.8395,
    longitude: 77.3824,
    skills: ['Agriculture', 'Food Processing', 'Post Harvest Management', 'Banana Pulp Processing'],
    educationRequired: 'Below 8th',
    nsqfLevel: 3,
    courseName: 'Fruits & Vegetables Processing Technician (FIC/Q0103)',
    provider: 'Theni District Farmers Producer Organisation (FPO)',
    careerGoal: 'entrepreneurship',
    estimatedMonthlyIncome: 16500,
    eligibility: ['Rural SC farmer / agricultural labourer', 'Self-help group membership'],
    description: 'Value addition for Theni banana and mango crops. PM-AJAY GIA grant supports dehydration equipment and solar dryers.',
    contactPhone: '+91 4546 244 800',
    contactEmail: 'fpo.theni@tn.nic.in',
    address: 'Mullai Periyar Agrotech Hub, Chinnamanur, Theni 625515',
    isVerified: true
  },
  {
    id: 'opp-tn-theni-05',
    name: 'Theni District Electrician & Solar Apprenticeship',
    type: 'apprenticeship',
    state: 'Tamil Nadu',
    district: 'Theni',
    city: 'Theni',
    latitude: 10.0180,
    longitude: 77.4690,
    skills: ['Electrical', 'Wiring', 'Solar Panel Installation', 'Meter Reading'],
    educationRequired: '10th Pass',
    nsqfLevel: 4,
    courseName: 'Domestic Electrician & Solar PV Helper',
    provider: 'TANGEDCO Sub-Division & NAPS Skill Partner',
    careerGoal: 'job',
    estimatedMonthlyIncome: 10500,
    eligibility: ['10th Pass / ITI Electrical', 'NAPS portal registration'],
    description: '12-month paid government apprenticeship with TANGEDCO distribution lines. Monthly government stipend plus certification.',
    contactPhone: '+91 4546 250 119',
    contactEmail: 'ee.theni@tnebnet.org',
    address: 'TANGEDCO Circle Office, NRT Road, Theni 625531',
    isVerified: true
  },
  {
    id: 'opp-tn-theni-06',
    name: 'Theni Dairy & Animal Husbandry Enterprise Pathway',
    type: 'livelihood',
    state: 'Tamil Nadu',
    district: 'Theni',
    city: 'Andipatti',
    latitude: 9.9920,
    longitude: 77.6250,
    skills: ['Agriculture', 'Cattle Care', 'Milk Testing', 'Fodder Cultivation'],
    educationRequired: 'Below 8th',
    nsqfLevel: 3,
    courseName: 'Dairy Farmer / Milk Production (AGR/Q4101)',
    provider: 'Aavin Dairy Cooperative & PM-AJAY District Cell',
    careerGoal: 'self-employment',
    estimatedMonthlyIncome: 17500,
    eligibility: ['Rural household', 'SC community preference'],
    description: 'Milch animal purchase support, automated milking kit grant under PM-AJAY GIA, and guaranteed daily procurement by Aavin.',
    contactPhone: '+91 4546 242 300',
    contactEmail: 'aavin.theni@tn.gov.in',
    address: 'Dairy Complex, Madurai Main Road, Andipatti, Theni 625512',
    isVerified: true
  },

  // ==========================================
  // TAMIL NADU - MADURAI
  // ==========================================
  {
    id: 'opp-tn-madurai-01',
    name: 'Madurai Govt ITI Welding & Fabrication Training',
    type: 'training',
    state: 'Tamil Nadu',
    district: 'Madurai',
    city: 'Madurai',
    latitude: 9.9390,
    longitude: 78.1380,
    skills: ['Welding', 'Metal Fabrication', 'Arc Welding', 'Safety Operations'],
    educationRequired: '8th Pass',
    nsqfLevel: 4,
    courseName: 'Manual Metal Arc Welder (CSC/Q0204)',
    provider: 'Government Industrial Training Institute (ITI) Madurai',
    careerGoal: 'job',
    estimatedMonthlyIncome: 16000,
    eligibility: ['8th pass minimum', 'Physical fitness for workshop duties'],
    description: 'Comprehensive 6-month hands-on welding course with qualification pack certification and placement tie-ups in automobile ancillaries.',
    contactPhone: '+91 452 253 0451',
    contactEmail: 'principal.itimdu@tn.gov.in',
    address: 'K.Pudur, Alagar Kovil Road, Madurai 625007',
    isVerified: true
  },
  {
    id: 'opp-tn-madurai-02',
    name: 'Madurai Automotive Service Technician',
    type: 'job',
    state: 'Tamil Nadu',
    district: 'Madurai',
    city: 'Madurai',
    latitude: 9.9120,
    longitude: 78.1050,
    skills: ['Automotive', 'Engine Repair', 'Brake Servicing', 'Electrical'],
    educationRequired: '10th Pass',
    nsqfLevel: 4,
    courseName: 'Four Wheeler Service Technician (ASC/Q1402)',
    provider: 'TVS Mobility Service Center',
    careerGoal: 'job',
    estimatedMonthlyIncome: 15500,
    eligibility: ['10th pass / ITI Motor Mechanic', 'Valid driver license a plus'],
    description: 'Immediate opening for junior auto technicians. Hands-on diagnostics, preventative maintenance, and OEM certification.',
    contactPhone: '+91 452 260 8800',
    contactEmail: 'hr@tvsmobility.com',
    address: 'Bypass Road, Ponmeni, Madurai 625016',
    isVerified: true
  },
  {
    id: 'opp-tn-madurai-03',
    name: 'Madurai Beauty & Wellness Self-Employment Hub',
    type: 'livelihood',
    state: 'Tamil Nadu',
    district: 'Madurai',
    city: 'Madurai',
    latitude: 9.9280,
    longitude: 78.1250,
    skills: ['Beauty & Wellness', 'Skin Care', 'Hair Styling', 'Bridal Grooming'],
    educationRequired: '8th Pass',
    nsqfLevel: 3,
    courseName: 'Assistant Beauty Therapist (BWS/Q0101)',
    provider: 'Madurai District Women Development Corporation',
    careerGoal: 'self-employment',
    estimatedMonthlyIncome: 19000,
    eligibility: ['Women SC applicants', 'Basic grooming interest'],
    description: 'Doorstep bridal and parlour setup kit provided under PM-AJAY GIA grant with beauty salon management training.',
    contactPhone: '+91 452 252 7111',
    contactEmail: 'mdu.women@tn.gov.in',
    address: 'Collectorate Complex, Madurai 625020',
    isVerified: true
  },
  {
    id: 'opp-tn-madurai-04',
    name: 'Madurai Solar Rooftop Installation Apprenticeship',
    type: 'apprenticeship',
    state: 'Tamil Nadu',
    district: 'Madurai',
    city: 'Thirumangalam',
    latitude: 9.8240,
    longitude: 77.9890,
    skills: ['Electrical', 'Solar Panel Installation', 'Inverter Wiring', 'Safety Audits'],
    educationRequired: '10th Pass',
    nsqfLevel: 4,
    courseName: 'Suryamitra Solar PV Technician',
    provider: 'SunEdison Green Energy & NAPS',
    careerGoal: 'job',
    estimatedMonthlyIncome: 11000,
    eligibility: ['10th pass', 'Comfortable with rooftop work'],
    description: 'On-the-job training installing residential and commercial rooftop solar arrays across Madurai district.',
    contactPhone: '+91 452 277 4001',
    contactEmail: 'naps@sunedisongreen.in',
    address: 'Industrial Corridor, Thirumangalam, Madurai 625706',
    isVerified: true
  },

  // ==========================================
  // TAMIL NADU - DINDIGUL
  // ==========================================
  {
    id: 'opp-tn-dindigul-01',
    name: 'Dindigul Food Processing & Fruit Preservation Training',
    type: 'training',
    state: 'Tamil Nadu',
    district: 'Dindigul',
    city: 'Dindigul',
    latitude: 10.3620,
    longitude: 77.9750,
    skills: ['Food Processing', 'Packaging', 'Hygiene Standards', 'Quality Testing'],
    educationRequired: '8th Pass',
    nsqfLevel: 3,
    courseName: 'Food Products Packaging Operator (FIC/Q7001)',
    provider: 'Gandhigram Rural Institute & MSME DI Dindigul',
    careerGoal: 'self-employment',
    estimatedMonthlyIncome: 15000,
    eligibility: ['8th pass minimum', 'Rural SC youth'],
    description: 'Hands-on training in fruit squash, jam, pickle, and bakery processing with FSSAI hygiene certification.',
    contactPhone: '+91 451 245 2371',
    contactEmail: 'gri-food@ruraluniv.ac.in',
    address: 'Gandhigram, Dindigul 624302',
    isVerified: true
  },
  {
    id: 'opp-tn-dindigul-02',
    name: 'Dindigul Lock & Hardware Assembly Machine Operator',
    type: 'job',
    state: 'Tamil Nadu',
    district: 'Dindigul',
    city: 'Dindigul',
    latitude: 10.3750,
    longitude: 77.9910,
    skills: ['Metal Fabrication', 'Assembly', 'Machine Operation', 'Quality Inspection'],
    educationRequired: '10th Pass',
    nsqfLevel: 3,
    courseName: 'Hardware Assembly Operator',
    provider: 'Dindigul Lock Artisans Industrial Society',
    careerGoal: 'job',
    estimatedMonthlyIncome: 14200,
    eligibility: ['10th pass', 'Dexterity with mechanical assembly'],
    description: 'Assemble precision brass locks and architectural hardware. Fixed monthly salary with statutory benefits.',
    contactPhone: '+91 451 242 1090',
    contactEmail: 'info@dindigullocks.org',
    address: 'SIDCO Industrial Estate, Nagal Nagar, Dindigul 624003',
    isVerified: true
  },
  {
    id: 'opp-tn-dindigul-03',
    name: 'Dindigul Organic Vermicomposting & Bio-fertilizer Enterprise',
    type: 'livelihood',
    state: 'Tamil Nadu',
    district: 'Dindigul',
    city: 'Oddanchatram',
    latitude: 10.4850,
    longitude: 77.7450,
    skills: ['Agriculture', 'Organic Farming', 'Soil Testing', 'Composting'],
    educationRequired: 'Below 8th',
    nsqfLevel: 3,
    courseName: 'Bio-Fertilizer & Vermicompost Producer',
    provider: 'Oddanchatram Vegetable Market Farmers Welfare Trust',
    careerGoal: 'entrepreneurship',
    estimatedMonthlyIncome: 20000,
    eligibility: ['Rural SC family', 'Availability of 500 sq ft land'],
    description: 'PM-AJAY GIA grant supports shade net, HDPE composting beds, and earthworm starter colonies for direct sale to vegetable growers.',
    contactPhone: '+91 451 240 0122',
    contactEmail: 'agri.dgl@tn.gov.in',
    address: 'Market Yard Complex, Oddanchatram, Dindigul 624619',
    isVerified: true
  },

  // ==========================================
  // TAMIL NADU - COIMBATORE
  // ==========================================
  {
    id: 'opp-tn-cbe-01',
    name: 'Coimbatore Precision CNC Machine Operator Training',
    type: 'training',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    city: 'Coimbatore',
    latitude: 11.0250,
    longitude: 76.9620,
    skills: ['CNC Machining', 'Tool Setting', 'Blueprint Reading', 'Quality Measurement'],
    educationRequired: '10th Pass',
    nsqfLevel: 4,
    courseName: 'CNC Operator Turning (CSC/Q0115)',
    provider: 'PSG Industrial Institute & Skill Development Center',
    careerGoal: 'job',
    estimatedMonthlyIncome: 18500,
    eligibility: ['10th Pass with Science/Math or ITI', 'Age 18-30'],
    description: 'State-of-the-art CNC turning and milling training. 90% direct placement record in Coimbatore pump and motor industries.',
    contactPhone: '+91 422 434 4000',
    contactEmail: 'admissions@psgtech.edu',
    address: 'Avinashi Road, Peelamedu, Coimbatore 641004',
    isVerified: true
  },
  {
    id: 'opp-tn-cbe-02',
    name: 'Coimbatore Pump & Motor Assembly Technician',
    type: 'job',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    city: 'Coimbatore',
    latitude: 11.0080,
    longitude: 76.9420,
    skills: ['Electrical', 'Motor Winding', 'Assembly', 'Testing'],
    educationRequired: '10th Pass',
    nsqfLevel: 4,
    courseName: 'Submersible Pump Assembler',
    provider: 'Aqua Submersible Pumps Pvt Ltd',
    careerGoal: 'job',
    estimatedMonthlyIncome: 16500,
    eligibility: ['10th pass / ITI Electrical or Fitter'],
    description: 'Assemble high-efficiency agricultural and domestic pump sets. Good career advancement and overtime incentives.',
    contactPhone: '+91 422 257 8890',
    contactEmail: 'hr@aquapumps.in',
    address: 'Thudiyalur Road, Saravanampatti, Coimbatore 641035',
    isVerified: true
  },
  {
    id: 'opp-tn-cbe-03',
    name: 'Coimbatore Micro-Boutique & Tailoring Collective',
    type: 'livelihood',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    city: 'Pollachi',
    latitude: 10.6580,
    longitude: 77.0080,
    skills: ['Tailoring', 'Embroidery', 'Boutique Management', 'Garment Finishing'],
    educationRequired: '8th Pass',
    nsqfLevel: 4,
    courseName: 'Custom Tailoring & Fashion Specialist',
    provider: 'Pollachi Coir & Textile Artisan Producer Co.',
    careerGoal: 'self-employment',
    estimatedMonthlyIncome: 21000,
    eligibility: ['SC women artisans', 'Basic stitching skills'],
    description: 'Incubation unit with motorized sewing machines, embroidery toolkits, and link to retail boutiques in Coimbatore city.',
    contactPhone: '+91 4259 223 344',
    contactEmail: 'pollachi.textiles@tn.nic.in',
    address: 'New Scheme Road, Pollachi, Coimbatore 642001',
    isVerified: true
  },
  {
    id: 'opp-tn-cbe-04',
    name: 'Coimbatore Auto Electrical Apprenticeship',
    type: 'apprenticeship',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    city: 'Coimbatore',
    latitude: 11.0420,
    longitude: 76.9950,
    skills: ['Automotive', 'Electrical', 'Battery Testing', 'Wiring Harness'],
    educationRequired: '10th Pass',
    nsqfLevel: 3,
    courseName: 'Auto Electrical & Electronics Helper',
    provider: 'Roots Industries & NAPS Hub',
    careerGoal: 'job',
    estimatedMonthlyIncome: 12000,
    eligibility: ['10th Pass', 'Aadhaar verified'],
    description: 'One-year structured apprenticeship in auto electrical harness and horn manufacturing.',
    contactPhone: '+91 422 432 1000',
    contactEmail: 'careers@roots.co.in',
    address: 'Ganapathy, Coimbatore 641006',
    isVerified: true
  },

  // ==========================================
  // TAMIL NADU - TIRUPPUR
  // ==========================================
  {
    id: 'opp-tn-tiruppur-01',
    name: 'Tiruppur Export Garment Sewing Machine Operator Training',
    type: 'training',
    state: 'Tamil Nadu',
    district: 'Tiruppur',
    city: 'Tiruppur',
    latitude: 11.1150,
    longitude: 77.3480,
    skills: ['Tailoring', 'Overlock Sewing', 'Flatlock Stitching', 'Garment Finishing'],
    educationRequired: '8th Pass',
    nsqfLevel: 4,
    courseName: 'Sewing Machine Operator - Knits (AMH/Q0301)',
    provider: 'NIFT-TEA Knitwear Fashion Institute',
    careerGoal: 'job',
    estimatedMonthlyIncome: 16000,
    eligibility: ['Age 18-35', 'Free training for SC beneficiaries under PM-AJAY'],
    description: 'Specialized 300-hour training in export-grade knitwear stitching with direct job placement in Tiruppur garment export factories.',
    contactPhone: '+91 421 247 4844',
    contactEmail: 'admissions@nifttea.ac.in',
    address: 'East Club Road, Tiruppur 641601',
    isVerified: true
  },
  {
    id: 'opp-tn-tiruppur-02',
    name: 'Tiruppur Knitwear Quality Checker & Line Supervisor',
    type: 'job',
    state: 'Tamil Nadu',
    district: 'Tiruppur',
    city: 'Tiruppur',
    latitude: 11.0980,
    longitude: 77.3320,
    skills: ['Tailoring', 'Quality Inspection', 'Fabric Testing', 'Garment Finishing'],
    educationRequired: '10th Pass',
    nsqfLevel: 4,
    courseName: 'Garment Quality Controller',
    provider: 'Poppys Knitwear Exports',
    careerGoal: 'job',
    estimatedMonthlyIncome: 17500,
    eligibility: ['10th pass / 12th pass', 'Eye for fabric flaws'],
    description: 'Ensure international AQL quality standards on garment export lines. Steady day shift with performance bonus.',
    contactPhone: '+91 421 221 0900',
    contactEmail: 'hr@poppysknits.com',
    address: 'Apparel Park, Angeripalayam, Tiruppur 641603',
    isVerified: true
  },
  {
    id: 'opp-tn-tiruppur-03',
    name: 'Tiruppur Apparel Micro-Enterprise Collective',
    type: 'livelihood',
    state: 'Tamil Nadu',
    district: 'Tiruppur',
    city: 'Avinashi',
    latitude: 11.1920,
    longitude: 77.2680,
    skills: ['Tailoring', 'Fabric Sourcing', 'Stitching', 'Boutique Setup'],
    educationRequired: '8th Pass',
    nsqfLevel: 4,
    courseName: 'Apparel Job-Work Entrepreneur',
    provider: 'Tiruppur District Rural Development Agency',
    careerGoal: 'self-employment',
    estimatedMonthlyIncome: 22000,
    eligibility: ['SC group or individual', 'PM-AJAY GIA toolkit applicant'],
    description: 'Sub-contract garment job-work unit. High demand for button holing, collar stitching, and children wear manufacturing.',
    contactPhone: '+91 421 247 1010',
    contactEmail: 'drda.tpr@tn.gov.in',
    address: 'Block Development Office, Avinashi, Tiruppur 641654',
    isVerified: true
  },
  {
    id: 'opp-tn-tiruppur-04',
    name: 'Tiruppur Textile Dyeing & Finishing Apprenticeship',
    type: 'apprenticeship',
    state: 'Tamil Nadu',
    district: 'Tiruppur',
    city: 'Tiruppur',
    latitude: 11.1220,
    longitude: 77.3620,
    skills: ['Food Processing', 'Chemical Processing', 'Fabric Testing', 'Machine Operation'],
    educationRequired: '10th Pass',
    nsqfLevel: 3,
    courseName: 'Textile Wet Processing Helper',
    provider: 'Netaji Apparel Park CETP',
    careerGoal: 'job',
    estimatedMonthlyIncome: 11500,
    eligibility: ['10th Pass', 'Health check clearance'],
    description: 'Learn zero-liquid discharge textile dyeing and garment washing operations under certified engineers.',
    contactPhone: '+91 421 248 8100',
    contactEmail: 'apprenticeship@netajipark.org',
    address: 'Netaji Apparel Park, New Tiruppur 641666',
    isVerified: true
  },

  // ==========================================
  // TAMIL NADU - CHENNAI
  // ==========================================
  {
    id: 'opp-tn-chennai-01',
    name: 'Chennai Digital CSC & Data Entry Training Hub',
    type: 'training',
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    latitude: 13.0850,
    longitude: 80.2750,
    skills: ['Computer/IT', 'Data Entry', 'MS Office', 'Internet Services', 'Typing'],
    educationRequired: '10th Pass',
    nsqfLevel: 4,
    courseName: 'Domestic Data Entry Operator (SSC/Q2212)',
    provider: 'NIELIT Chennai & TAHDCO',
    careerGoal: 'job',
    estimatedMonthlyIncome: 16000,
    eligibility: ['10th Pass minimum', 'SC candidate free sponsorship under TAHDCO'],
    description: 'Government certified computer operations and data entry course with typing speed certification and e-Governance kiosk training.',
    contactPhone: '+91 44 2442 1445',
    contactEmail: 'dir-chennai@nielit.gov.in',
    address: 'ISTE Complex, Gandhi Mandapam Road, Chennai 600025',
    isVerified: true
  },
  {
    id: 'opp-tn-chennai-02',
    name: 'Chennai Automotive Assembly Line Technician',
    type: 'job',
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Sriperumbudur',
    latitude: 12.9680,
    longitude: 79.9450,
    skills: ['Automotive', 'Assembly', 'Pneumatic Tools', 'Quality Inspection'],
    educationRequired: '10th Pass',
    nsqfLevel: 4,
    courseName: 'Automotive Assembly Operator (ASC/Q3601)',
    provider: 'Hyundai Motor India / Tier-1 Supplier',
    careerGoal: 'job',
    estimatedMonthlyIncome: 19500,
    eligibility: ['10th / 12th / ITI', 'Age 18-28'],
    description: 'Vehicle assembly operations in modern automotive manufacturing plant with subsidized canteen, transport, and insurance.',
    contactPhone: '+91 44 4710 0000',
    contactEmail: 'careers@hyundai.co.in',
    address: 'SIPCOT Industrial Park, Sriperumbudur, Chennai 602105',
    isVerified: true
  },
  {
    id: 'opp-tn-chennai-03',
    name: 'Chennai Retail Sales Associate Apprenticeship',
    type: 'apprenticeship',
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    latitude: 13.0600,
    longitude: 80.2450,
    skills: ['Computer/IT', 'Customer Service', 'Billing & POS', 'Inventory Management'],
    educationRequired: '10th Pass',
    nsqfLevel: 4,
    courseName: 'Retail Trainee Associate (RAS/Q0103)',
    provider: 'Reliance Retail & NAPS Skill Partner',
    careerGoal: 'job',
    estimatedMonthlyIncome: 12500,
    eligibility: ['10th pass / 12th pass', 'Pleasant communication'],
    description: 'Store operations, customer assistance, POS billing, and shelf replenishment in modern supermarket formats.',
    contactPhone: '+91 44 2820 4500',
    contactEmail: 'retail.careers@reliance.com',
    address: 'Nungambakkam High Road, Chennai 600034',
    isVerified: true
  },
  {
    id: 'opp-tn-chennai-04',
    name: 'Chennai Construction Electrician & Wiring Unit',
    type: 'job',
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    latitude: 13.0100,
    longitude: 80.2100,
    skills: ['Electrical', 'Construction', 'Wiring', 'Safety Standards'],
    educationRequired: '8th Pass',
    nsqfLevel: 4,
    courseName: 'Construction Electrician (CON/Q0601)',
    provider: 'L&T Construction Skill Training Institute',
    careerGoal: 'job',
    estimatedMonthlyIncome: 17000,
    eligibility: ['8th pass', 'Physical stamina for site work'],
    description: 'Commercial building conduit piping, wiring, distribution board termination, and earthing installation.',
    contactPhone: '+91 44 2252 8000',
    contactEmail: 'csti@lntecc.com',
    address: 'Mount Poonamallee Road, Manapakkam, Chennai 600089',
    isVerified: true
  },

  // ==========================================
  // TAMIL NADU - SALEM
  // ==========================================
  {
    id: 'opp-tn-salem-01',
    name: 'Salem Steel & Metal Fabrication Training Center',
    type: 'training',
    state: 'Tamil Nadu',
    district: 'Salem',
    city: 'Salem',
    latitude: 11.6680,
    longitude: 78.1490,
    skills: ['Welding', 'Metal Fabrication', 'Grinding', 'Gas Cutting'],
    educationRequired: '8th Pass',
    nsqfLevel: 3,
    courseName: 'Fitter Fabrication (CSC/Q0303)',
    provider: 'SAIL Salem Steel Plant Skill Development Center',
    careerGoal: 'job',
    estimatedMonthlyIncome: 15500,
    eligibility: ['8th pass', 'SC youth skill development scheme'],
    description: 'Hands-on training in structural steel fabrication, drilling, tack welding, and industrial assembly.',
    contactPhone: '+91 427 238 2000',
    contactEmail: 'sdc.ssp@sail.in',
    address: 'Steel Plant Complex, Salem 636013',
    isVerified: true
  },
  {
    id: 'opp-tn-salem-02',
    name: 'Salem Sago & Starch Processing Operator',
    type: 'job',
    state: 'Tamil Nadu',
    district: 'Salem',
    city: 'Attur',
    latitude: 11.5950,
    longitude: 78.5980,
    skills: ['Food Processing', 'Machine Operation', 'Packaging', 'Hygiene Standards'],
    educationRequired: 'Below 8th',
    nsqfLevel: 2,
    courseName: 'Agro Processing Helper',
    provider: 'SAGOSERVE Cooperative Society',
    careerGoal: 'job',
    estimatedMonthlyIncome: 13000,
    eligibility: ['Basic physical fitness', 'Local resident'],
    description: 'Tapioca crushing, starch separation, and automated drying operations with steady yearly employment.',
    contactPhone: '+91 427 244 8500',
    contactEmail: 'admin@sagoserve.com',
    address: 'Sagoserve Road, Jagirammapalayam, Salem 636302',
    isVerified: true
  },
  {
    id: 'opp-tn-salem-03',
    name: 'Salem Powerloom Maintenance Apprenticeship',
    type: 'apprenticeship',
    state: 'Tamil Nadu',
    district: 'Salem',
    city: 'Salem',
    latitude: 11.6520,
    longitude: 78.1350,
    skills: ['Carpentry', 'Electrical', 'Machine Operation', 'Textile Weaving'],
    educationRequired: '10th Pass',
    nsqfLevel: 4,
    courseName: 'Shuttleless Weaving Machine Technician',
    provider: 'Salem Textile Weavers Federation',
    careerGoal: 'job',
    estimatedMonthlyIncome: 11000,
    eligibility: ['10th Pass / ITI Mechanical'],
    description: 'Learn mechanical timing, reed adjustment, and electrical drive maintenance on modern rapier powerlooms.',
    contactPhone: '+91 427 226 0140',
    contactEmail: 'weavers.salem@tn.gov.in',
    address: 'Ammapet Main Road, Salem 636003',
    isVerified: true
  },
  {
    id: 'opp-tn-salem-04',
    name: 'Salem Poultry & Dairy Cooperative Pathway',
    type: 'livelihood',
    state: 'Tamil Nadu',
    district: 'Salem',
    city: 'Sankari',
    latitude: 11.4820,
    longitude: 77.8680,
    skills: ['Agriculture', 'Cattle Care', 'Poultry Care', 'Feed Management'],
    educationRequired: 'Below 8th',
    nsqfLevel: 3,
    courseName: 'Broiler & Layer Poultry Farmer (AGR/Q4301)',
    provider: 'Salem District Animal Husbandry Department',
    careerGoal: 'self-employment',
    estimatedMonthlyIncome: 18500,
    eligibility: ['Rural SC beneficiary', 'PM-AJAY GIA livestock scheme'],
    description: '100-bird backyard broiler unit grant with automated feeder, veterinary vaccination support, and contract buyback.',
    contactPhone: '+91 427 241 5500',
    contactEmail: 'dah.salem@tn.gov.in',
    address: 'Veterinary Hospital Complex, Sankari, Salem 637301',
    isVerified: true
  },

  // ==========================================
  // TAMIL NADU - ERODE
  // ==========================================
  {
    id: 'opp-tn-erode-01',
    name: 'Erode Turmeric & Spice Processing Apprenticeship',
    type: 'apprenticeship',
    state: 'Tamil Nadu',
    district: 'Erode',
    city: 'Erode',
    latitude: 11.3450,
    longitude: 77.7250,
    skills: ['Agriculture', 'Food Processing', 'Grinding', 'Packaging'],
    educationRequired: '8th Pass',
    nsqfLevel: 3,
    courseName: 'Spice Processing Technician (FIC/Q8001)',
    provider: 'Erode Turmeric Merchants Association & NAPS',
    careerGoal: 'job',
    estimatedMonthlyIncome: 10800,
    eligibility: ['8th pass', 'Good health'],
    description: 'Learn turmeric boiling, sun-drying, polishing, and commercial packaging in India’s leading turmeric hub.',
    contactPhone: '+91 424 222 1400',
    contactEmail: 'turmeric.erode@tn.nic.in',
    address: 'Perundurai Road, Erode 638011',
    isVerified: true
  },
  {
    id: 'opp-tn-erode-02',
    name: 'Erode Textile Weaving & Garment Stitching Center',
    type: 'training',
    state: 'Tamil Nadu',
    district: 'Erode',
    city: 'Bhavani',
    latitude: 11.4500,
    longitude: 77.6850,
    skills: ['Tailoring', 'Textile Weaving', 'Sewing', 'Pattern Making'],
    educationRequired: '8th Pass',
    nsqfLevel: 4,
    courseName: 'Handloom & Carpet Weaver / Tailor',
    provider: 'Govt Handloom Training Center Bhavani',
    careerGoal: 'self-employment',
    estimatedMonthlyIncome: 16000,
    eligibility: ['8th pass', 'SC artisan priority'],
    description: 'Traditional Bhavani jamakkalam weaving combined with modern sewing and home furnishings stitching.',
    contactPhone: '+91 424 233 4500',
    contactEmail: 'handlooms.bhavani@tn.gov.in',
    address: 'Kaveri Road, Bhavani, Erode 638301',
    isVerified: true
  },
  {
    id: 'opp-tn-erode-03',
    name: 'Erode Agricultural Equipment Service Technician',
    type: 'job',
    state: 'Tamil Nadu',
    district: 'Erode',
    city: 'Perundurai',
    latitude: 11.2780,
    longitude: 77.5850,
    skills: ['Automotive', 'Welding', 'Engine Repair', 'Electrical'],
    educationRequired: '10th Pass',
    nsqfLevel: 4,
    courseName: 'Tractor & Power Tiller Mechanic (AGR/Q1102)',
    provider: 'Mahindra Farm Equipment Service Hub',
    careerGoal: 'job',
    estimatedMonthlyIncome: 17000,
    eligibility: ['10th pass / ITI Mechanic'],
    description: 'Repair and service diesel tractors, harvesters, and irrigation pumps across rural agricultural belts.',
    contactPhone: '+91 424 253 6000',
    contactEmail: 'service@erodefarmequip.com',
    address: 'SIPCOT Industrial Growth Estate, Perundurai, Erode 638052',
    isVerified: true
  },

  // ==========================================
  // ANDHRA PRADESH - VIZIANAGARAM, VIJAYAWADA, GUNTUR, TIRUPATI
  // ==========================================
  {
    id: 'opp-ap-vzm-01',
    name: 'Vizianagaram Rural Garment Stitching Center',
    type: 'training',
    state: 'Andhra Pradesh',
    district: 'Vizianagaram',
    city: 'Vizianagaram',
    latitude: 18.1120,
    longitude: 83.4020,
    skills: ['Tailoring', 'Hand Stitching', 'Garment Finishing', 'Pattern Cutting'],
    educationRequired: '8th Pass',
    nsqfLevel: 4,
    courseName: 'Sewing Machine Operator (AMH/Q0301)',
    provider: 'APSSDC & District Youth Training Center',
    careerGoal: 'self-employment',
    estimatedMonthlyIncome: 14000,
    eligibility: ['8th pass', 'SC beneficiary under PM-AJAY GIA'],
    description: 'Motorized sewing operations with motorized sewing kit grant sanction upon course completion.',
    contactPhone: '+91 8922 276 500',
    contactEmail: 'apssdc.vzm@ap.gov.in',
    address: 'Cantonment, Vizianagaram 535003',
    isVerified: true
  },
  {
    id: 'opp-ap-vzm-02',
    name: 'Vizianagaram Jute & Handloom Enterprise Hub',
    type: 'livelihood',
    state: 'Andhra Pradesh',
    district: 'Vizianagaram',
    city: 'Nellimarla',
    latitude: 18.1650,
    longitude: 83.4350,
    skills: ['Tailoring', 'Jute Bag Making', 'Weaving', 'Boutique Setup'],
    educationRequired: 'Below 8th',
    nsqfLevel: 3,
    courseName: 'Jute Artisan & Bag Manufacturer',
    provider: 'AP Handicrafts Development Corporation',
    careerGoal: 'self-employment',
    estimatedMonthlyIncome: 16500,
    eligibility: ['SC rural artisan', 'PM-AJAY GIA grant applicant'],
    description: 'Eco-friendly jute shopping bag and lifestyle product crafting with direct market linkage to supermarket chains.',
    contactPhone: '+91 8922 244 110',
    contactEmail: 'lepapakshi.vzm@ap.gov.in',
    address: 'Near Jute Mill, Nellimarla, Vizianagaram 535217',
    isVerified: true
  },
  {
    id: 'opp-ap-vjw-01',
    name: 'Vijayawada Auto Electrical & EV Battery Servicing',
    type: 'job',
    state: 'Andhra Pradesh',
    district: 'Vijayawada',
    city: 'Vijayawada',
    latitude: 16.5120,
    longitude: 80.6550,
    skills: ['Electrical', 'Automotive', 'Battery Servicing', 'EV Maintenance'],
    educationRequired: '10th Pass',
    nsqfLevel: 4,
    courseName: 'Electric Vehicle Service Lead (ASC/Q1424)',
    provider: 'Auto Nagar Commercial Fleet Service Hub',
    careerGoal: 'job',
    estimatedMonthlyIncome: 18000,
    eligibility: ['10th Pass / ITI Electrical'],
    description: 'Commercial 3-wheeler and electric auto maintenance. Diagnostic tools and battery pack replacement.',
    contactPhone: '+91 866 254 3300',
    contactEmail: 'autonagar.vjw@ap.gov.in',
    address: 'Auto Nagar Industrial Estate, Vijayawada 520007',
    isVerified: true
  },
  {
    id: 'opp-ap-gnt-01',
    name: 'Guntur Chilli & Agro Processing Unit Operator',
    type: 'job',
    state: 'Andhra Pradesh',
    district: 'Guntur',
    city: 'Guntur',
    latitude: 16.3120,
    longitude: 80.4450,
    skills: ['Agriculture', 'Food Processing', 'Packaging', 'Grading'],
    educationRequired: '8th Pass',
    nsqfLevel: 3,
    courseName: 'Spice Grinding & Packing Operator',
    provider: 'Guntur Agricultural Market Committee (AMC)',
    careerGoal: 'job',
    estimatedMonthlyIncome: 15000,
    eligibility: ['8th pass minimum'],
    description: 'Automated spice cleaning, grading, grinding, and cold storage monitoring in Asia’s largest chilli market.',
    contactPhone: '+91 863 223 4400',
    contactEmail: 'amc.guntur@ap.gov.in',
    address: 'Market Yard, Mirchi Yard, Guntur 522004',
    isVerified: true
  },
  {
    id: 'opp-ap-tpt-01',
    name: 'Tirupati Hospitality & Food Service Associate',
    type: 'job',
    state: 'Andhra Pradesh',
    district: 'Tirupati',
    city: 'Tirupati',
    latitude: 13.6350,
    longitude: 79.4250,
    skills: ['Food Processing', 'Customer Service', 'Hygiene Standards', 'Inventory Management'],
    educationRequired: '10th Pass',
    nsqfLevel: 4,
    courseName: 'Food & Beverage Service Steward (THC/Q0301)',
    provider: 'TTD Hospitality Services / Hotel Fortune',
    careerGoal: 'job',
    estimatedMonthlyIncome: 16500,
    eligibility: ['10th pass', 'Good hygiene habits'],
    description: 'Guest hosting, buffet presentation, and food service operations in high-footfall pilgrim hotels.',
    contactPhone: '+91 877 228 7777',
    contactEmail: 'careers@tirupatihotels.com',
    address: 'Renigunta Road, Tirupati 517501',
    isVerified: true
  },

  // ==========================================
  // KARNATAKA - BENGALURU, MYSURU
  // ==========================================
  {
    id: 'opp-ka-blr-01',
    name: 'Bengaluru Electronics PCB Assembly Technician',
    type: 'job',
    state: 'Karnataka',
    district: 'Bengaluru',
    city: 'Bengaluru',
    latitude: 12.9850,
    longitude: 77.6050,
    skills: ['Electrical', 'Computer/IT', 'Soldering', 'Quality Testing'],
    educationRequired: '10th Pass',
    nsqfLevel: 4,
    courseName: 'SMT Assembly Operator (ELE/Q5101)',
    provider: 'Peenya Industrial Electronics Association',
    careerGoal: 'job',
    estimatedMonthlyIncome: 19000,
    eligibility: ['10th pass / ITI', 'Fine motor coordination'],
    description: 'Assemble printed circuit boards for smart meters, IoT devices, and automotive controllers in air-conditioned cleanrooms.',
    contactPhone: '+91 80 2839 5000',
    contactEmail: 'jobs@peenyaelectronics.com',
    address: 'Peenya 2nd Stage, Bengaluru 560058',
    isVerified: true
  },
  {
    id: 'opp-ka-blr-02',
    name: 'Bengaluru Digital Skills & IT Data Operations',
    type: 'training',
    state: 'Karnataka',
    district: 'Bengaluru',
    city: 'Bengaluru',
    latitude: 12.9350,
    longitude: 77.6200,
    skills: ['Computer/IT', 'Data Entry', 'MS Office', 'English Typing'],
    educationRequired: '12th Pass',
    nsqfLevel: 5,
    courseName: 'Data Analytics & Digital Operations (SSC/Q2102)',
    provider: 'Karnataka Skill Development Corporation (KSDC)',
    careerGoal: 'job',
    estimatedMonthlyIncome: 22000,
    eligibility: ['12th pass / Graduate', 'SC youth free scholarship'],
    description: 'Fast-track 4-month program in data cleaning, spreadsheet modeling, and business process support with tech company hiring partners.',
    contactPhone: '+91 80 2234 1200',
    contactEmail: 'info@ksdc.kar.nic.in',
    address: 'Koramangala 4th Block, Bengaluru 560034',
    isVerified: true
  },
  {
    id: 'opp-ka-mys-01',
    name: 'Mysuru Silk Weaving & Garment Apprenticeship',
    type: 'apprenticeship',
    state: 'Karnataka',
    district: 'Mysuru',
    city: 'Mysuru',
    latitude: 12.3020,
    longitude: 76.6450,
    skills: ['Tailoring', 'Textile Weaving', 'Hand Stitching', 'Garment Finishing'],
    educationRequired: '8th Pass',
    nsqfLevel: 3,
    courseName: 'Jacquard Silk Weaver / Garment Finisher',
    provider: 'Karnataka Silk Industries Corporation (KSIC)',
    careerGoal: 'self-employment',
    estimatedMonthlyIncome: 12000,
    eligibility: ['8th pass', 'Interest in traditional silk crafts'],
    description: 'Learn authentic Mysore silk loom setting, jacquard pattern design, and high-value saree finishing with monthly stipend.',
    contactPhone: '+821 248 1800',
    contactEmail: 'mysuresilk@ksic.gov.in',
    address: 'Mananthody Road, Mysuru 570008',
    isVerified: true
  },

  // ==========================================
  // KERALA - KOCHI, THIRUVANANTHAPURAM
  // ==========================================
  {
    id: 'opp-kl-koc-01',
    name: 'Kochi Marine & Seafood Processing Facility',
    type: 'job',
    state: 'Kerala',
    district: 'Kochi',
    city: 'Kochi',
    latitude: 9.9380,
    longitude: 76.2750,
    skills: ['Food Processing', 'Cold Chain Management', 'Packaging', 'Hygiene Standards'],
    educationRequired: '8th Pass',
    nsqfLevel: 3,
    courseName: 'Seafood Processing Technician (FIC/Q4001)',
    provider: 'Marine Products Export Development Authority (MPEDA)',
    careerGoal: 'job',
    estimatedMonthlyIncome: 17500,
    eligibility: ['8th pass', 'Vaccinated for food handling'],
    description: 'Hygienic prawn grading, flash freezing, vacuum packaging, and export shipment documentation at Cochin Port Trust premises.',
    contactPhone: '+91 484 231 1900',
    contactEmail: 'mpeda@mpeda.gov.in',
    address: 'Willingdon Island, Kochi 682003',
    isVerified: true
  },
  {
    id: 'opp-kl-tvm-01',
    name: 'Thiruvananthapuram Ayurvedic & Wellness Therapist Training',
    type: 'training',
    state: 'Kerala',
    district: 'Thiruvananthapuram',
    city: 'Thiruvananthapuram',
    latitude: 8.5280,
    longitude: 76.9420,
    skills: ['Beauty & Wellness', 'Skin Care', 'Therapeutic Massage', 'Herb Processing'],
    educationRequired: '10th Pass',
    nsqfLevel: 4,
    courseName: 'Ayurvedic Spa & Wellness Therapist (BWS/Q0202)',
    provider: 'Kerala State Institute of Tourism and Travel Studies (KITTS)',
    careerGoal: 'self-employment',
    estimatedMonthlyIncome: 20000,
    eligibility: ['10th pass', 'Empathetic communication'],
    description: 'Government certified Ayurvedic massage, herbal oil preparation, and wellness clinic therapy with high domestic and Gulf demand.',
    contactPhone: '+91 471 232 9460',
    contactEmail: 'kitts@keralatourism.org',
    address: 'Thycaud, Thiruvananthapuram 695014',
    isVerified: true
  },

  // ==========================================
  // UTTAR PRADESH - SITAPUR (Existing Demo)
  // ==========================================
  {
    id: 'opp-up-stp-01',
    name: 'Sitapur Agro-Biomass & Vermicompost Unit',
    type: 'livelihood',
    state: 'Uttar Pradesh',
    district: 'Sitapur',
    city: 'Sitapur',
    latitude: 27.5720,
    longitude: 80.6880,
    skills: ['Agriculture', 'Cattle Care', 'Soil Preparation', 'Organic Farming'],
    educationRequired: 'Below 8th',
    nsqfLevel: 3,
    courseName: 'Bio-Fertilizer & Vermicompost Producer',
    provider: 'Sitapur Krishi Vigyan Kendra & PM-AJAY Cell',
    careerGoal: 'self-employment',
    estimatedMonthlyIncome: 16000,
    eligibility: ['Rural SC farmer / agricultural labourer', 'PM-AJAY GIA applicant'],
    description: 'Conversion of sugarcane crop residue and cow dung into certified vermicompost manure. Full equipment grant support.',
    contactPhone: '+91 5862 242 100',
    contactEmail: 'kvk.sitapur@icar.gov.in',
    address: 'Mahmudabad Road, Sitapur 261001',
    isVerified: true
  },

  // ==========================================
  // BIHAR - GAYA (Existing Demo)
  // ==========================================
  {
    id: 'opp-br-gaya-01',
    name: 'Gaya Digital Literacy & Typing Center',
    type: 'training',
    state: 'Bihar',
    district: 'Gaya',
    city: 'Gaya',
    latitude: 24.7960,
    longitude: 85.0080,
    skills: ['Computer/IT', 'English Typing', 'Data Entry', 'MS Office Basics'],
    educationRequired: '10th Pass',
    nsqfLevel: 4,
    courseName: 'Domestic Data Entry Operator (SSC/Q2212)',
    provider: 'Bihar Skill Development Mission (BSDM) Kushal Yuva Program',
    careerGoal: 'job',
    estimatedMonthlyIncome: 14500,
    eligibility: ['10th Pass', 'Age 15-28'],
    description: 'Digital computer training, typing speed enhancement, and CSC digital kiosk operations under state skill program.',
    contactPhone: '+91 631 222 5500',
    contactEmail: 'bsdm.gaya@bihar.gov.in',
    address: 'Civil Lines, Near Collectorate, Gaya 823001',
    isVerified: true
  },

  // ==========================================
  // MAHARASHTRA - SOLAPUR (Existing Demo)
  // ==========================================
  {
    id: 'opp-mh-sol-01',
    name: 'Solapur Doorstep Beauty & Cosmetology Hub',
    type: 'livelihood',
    state: 'Maharashtra',
    district: 'Solapur',
    city: 'Solapur',
    latitude: 17.6650,
    longitude: 75.9120,
    skills: ['Beauty & Wellness', 'Skin Care', 'Hair Styling', 'Threading & Waxing'],
    educationRequired: '8th Pass',
    nsqfLevel: 4,
    courseName: 'Assistant Beauty Therapist & Salon Entrepreneur',
    provider: 'Solapur Municipal Corporation & PM-AJAY Cell',
    careerGoal: 'self-employment',
    estimatedMonthlyIncome: 20000,
    eligibility: ['SC women candidates', 'Prior basic parlour work'],
    description: 'Electric facial steamers, waxing kits, hair styling dryers, and bridal makeup toolkit grant under PM-AJAY GIA scheme.',
    contactPhone: '+91 217 274 0300',
    contactEmail: 'smc.welfare@maharashtra.gov.in',
    address: 'Old Poona Naka, Solapur 413001',
    isVerified: true
  }
];

export const AVAILABLE_SKILLS_FILTER = [
  'Tailoring',
  'Welding',
  'Carpentry',
  'Electrical',
  'Agriculture',
  'Food Processing',
  'Computer/IT',
  'Beauty & Wellness',
  'Automotive',
  'Construction'
];
